# frozen_string_literal: true

source "https://rubygems.org"

gem "hanami", "~> 2.0.0.beta"
gem "hanami-router", "~> 2.0.0.beta"
gem "hanami-controller", "~> 2.0.0.beta"
gem "hanami-validations", "~> 2.0.0.beta"

gem "dry-types", "~> 1.0", ">= 1.6.1"
gem "puma"
gem "rake"

group :development, :test do
  gem "dotenv"
  gem 'standardrb'
end

group :cli, :development do
  gem "hanami-reloader"
end

group :cli, :development, :test do
  gem "hanami-rspec"
end

group :development do
  gem "guard-puma"
end


group :test do
  gem "rack-test"
end

